warn about missing extras

diff --git a/etc/common b/etc/common
--- a/etc/common
+++ b/etc/common
@@ -116,6 +116,15 @@ for extra in ${EXTRAS}; do
         "
         export GRIMA_EXTRAS
 
+        if [ ! -f "${TOPLEVEL}"/etc/common ]; then
+                echo -n "ERROR: Unable to locate ${extra} in any one of"
+                for location in ${LOCATIONS}; do
+                        echo -n " ${location}"
+                done
+                echo
+                exit 1
+        fi
+
         . "${TOPLEVEL}"/etc/common
 done
 
